services:
    kafka:
        image: bitnami/kafka:latest
        ports:
            - '9092:9092'
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_BROKER_ID: 1
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            ALLOW_PLAINTEXT_LISTENER: 'yes'
        depends_on:
            - zookeeper

    zookeeper:
        image: bitnami/zookeeper:latest
        ports:
            - '2181:2181'
        environment:
            ALLOW_ANONYMOUS_LOGIN: 'yes'

    unit-tests:
        image: golang:latest
        command: ['/bin/sh', '-c', "go test $(go list ./... | grep -v '/test')"]
        depends_on:
            - kafka
            - zookeeper
        volumes:
            - .:/app
        working_dir: /app
